# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

curves_cpp <- function(Linf, locperiodC, tw, K, ML, modday, sdate, sML, birthdaycurve) {
    .Call('ELEFAN_curves_cpp', PACKAGE = 'ELEFAN', Linf, locperiodC, tw, K, ML, modday, sdate, sML, birthdaycurve)
}

